In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("/content/wellbot_realistic_100k.csv")

In [3]:
data.head()

,user_id,age,gender,country,height_cm,weight_kg,bmi,heart_rate,blood_pressure_sys,blood_pressure_dia,...,calorie_intake,sleep_hours,sleep_efficiency,sleep_quality,water_intake_L,hydration_score,stress_level,mood_score,emotion,recommendation
0,U0104242,32.0,Male,Germany,174.5,79.5,26.4,74.0,102,69,...,2455,6.51,83.7,4.7,2.42,8.1,3,4.2,Sad,Add light exercise daily
1,U0199677,34.0,Male,Japan,169.3,65.7,22.0,59.0,120,69,...,2272,6.48,87.0,4.6,2.21,7.4,4,2.7,Stressed,Meditation & relaxation recommended | Add ligh...
2,U0140200,79.0,Male,India,171.1,84.0,29.2,82.0,155,87,...,2618,5.21,85.4,3.3,1.86,6.2,2,4.8,Sad,Increase sleep duration | Add light exercise d...
3,U0132815,57.0,Male,India,163.4,79.5,29.6,76.0,139,90,...,2673,8.02,86.7,3.8,1.99,6.6,4,3.7,Stressed,Meditation & relaxation recommended
4,U0408698,77.0,Male,India,158.5,51.4,21.4,70.0,133,79,...,2266,5.19,91.1,3.9,1.73,5.8,4,1.5,Stressed,Meditation & relaxation recommended | Increase...

In [4]:
data.columns

Index(['user_id', 'age', 'gender', 'country', 'height_cm', 'weight_kg', 'bmi',
       'heart_rate', 'blood_pressure_sys', 'blood_pressure_dia',
       'activity_type', 'activity_minutes', 'steps', 'calorie_intake',
       'sleep_hours', 'sleep_efficiency', 'sleep_quality', 'water_intake_L',
       'hydration_score', 'stress_level', 'mood_score', 'emotion',
       'recommendation'],
      dtype='object')

In [5]:
data.shape

(89579, 23)

In [6]:
data.isnull()

,user_id,age,gender,country,height_cm,weight_kg,bmi,heart_rate,blood_pressure_sys,blood_pressure_dia,...,calorie_intake,sleep_hours,sleep_efficiency,sleep_quality,water_intake_L,hydration_score,stress_level,mood_score,emotion,recommendation
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89574,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
89575,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
89576,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
89577,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
89578,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
data.isnull().sum()

user_id               0
age                   6
gender                0
country               0
height_cm             5
weight_kg             0
bmi                   0
heart_rate            5
blood_pressure_sys    0
blood_pressure_dia    0
activity_type         0
activity_minutes      0
steps                 0
calorie_intake        0
sleep_hours           0
sleep_efficiency      0
sleep_quality         0
water_intake_L        0
hydration_score       0
stress_level          0
mood_score            0
emotion               0
recommendation        0
dtype: int64

In [8]:
data['age']=data['age'].fillna(data['age'].mean())
data['height_cm']=data['height_cm'].fillna(data['height_cm'].mean())
data['heart_rate']=data['heart_rate'].fillna(data['heart_rate'].mean())

In [9]:
data.isnull().sum()

user_id               0
age                   0
gender                0
country               0
height_cm             0
weight_kg             0
bmi                   0
heart_rate            0
blood_pressure_sys    0
blood_pressure_dia    0
activity_type         0
activity_minutes      0
steps                 0
calorie_intake        0
sleep_hours           0
sleep_efficiency      0
sleep_quality         0
water_intake_L        0
hydration_score       0
stress_level          0
mood_score            0
emotion               0
recommendation        0
dtype: int64

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89579 entries, 0 to 89578
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id             89579 non-null  object
 1   age                 89579 non-null  float64
 2   gender              89579 non-null  object
 3   country             89579 non-null  object
 4   height_cm           89579 non-null  float64
 5   weight_kg           89579 non-null  float64
 6   bmi                 89579 non-null  float64
 7   heart_rate          89579 non-null  float64
 8   blood_pressure_sys  89579 non-null  int64
 9   blood_pressure_dia  89579 non-null  int64
 10  activity_type       89579 non-null  object
 11  activity_minutes    89579 non-null  int64
 12  steps               89579 non-null  int64
 13  calorie_intake      89579 non-null  int64
 14  sleep_hours         89579 non-null  float64
 15  sleep_efficiency    89579 non-null  float64
 16  sleep_quality       89579 non-null  float64
 17  water_intake_L      89579 non-null  float64
 18  hydration_score     89579 non-null  float64
 19  stress_level        89579 non-null  int64
 20  mood_score          89579 non-null  float64
 21  emotion             89579 non-null  object
 22  recommendation      89579 non-null  object
dtypes: float64(11), int64(6), object(6)
memory usage: 15.7+ MB

In [11]:
data.describe()

,age,height_cm,weight_kg,bmi,heart_rate,blood_pressure_sys,blood_pressure_dia,activity_minutes,steps,calorie_intake,sleep_hours,sleep_efficiency,sleep_quality,water_intake_L,hydration_score,stress_level,mood_score
count,89579.000000,89579.000000,89579.000000,89579.000000,89579.000000,89579.000000,89579.000000,89579.000000,89579.000000,89579.000000,89579.000000,89579.000000,89579.000000,89579.000000,89579.000000,89579.000000,89579.000000
mean,48.490103,167.662227,73.097559,25.837226,70.386094,121.091428,74.743701,34.136405,5342.225778,2467.244823,6.816371,84.071051,4.097472,2.313466,7.665919,3.282231,3.374945
std,17.885433,10.053346,15.800806,4.205527,6.233491,12.235520,7.189723,17.820027,3080.276540,356.293812,1.013298,5.082140,1.218291,0.454610,1.425226,1.230508,1.951485
min,18.000000,140.000000,40.000000,16.000000,50.000000,90.000000,50.000000,5.000000,200.000000,1258.000000,3.500000,60.700000,1.000000,0.800000,2.700000,1.000000,1.000000
25%,33.000000,160.500000,61.600000,22.900000,66.000000,112.000000,70.000000,21.000000,2944.000000,2215.000000,6.130000,80.600000,3.300000,2.010000,6.700000,2.000000,1.500000
50%,48.000000,167.300000,71.800000,25.700000,70.000000,121.000000,75.000000,33.000000,4834.000000,2462.000000,6.810000,84.100000,4.100000,2.310000,7.700000,3.000000,3.200000
75%,64.000000,174.700000,83.300000,28.600000,75.000000,130.000000,80.000000,46.000000,7353.000000,2712.000000,7.500000,87.500000,4.900000,2.620000,8.700000,4.000000,4.800000
max,79.000000,200.000000,154.100000,40.000000,98.000000,169.000000,108.000000,120.000000,19818.000000,3846.000000,10.000000,98.000000,9.600000,4.190000,10.000000,5.000000,10.000000

In [12]:
data.dtypes

user_id                object
age                   float64
gender                 object
country                object
height_cm             float64
weight_kg             float64
bmi                   float64
heart_rate            float64
blood_pressure_sys      int64
blood_pressure_dia      int64
activity_type          object
activity_minutes        int64
steps                   int64
calorie_intake          int64
sleep_hours           float64
sleep_efficiency      float64
sleep_quality         float64
water_intake_L        float64
hydration_score       float64
stress_level            int64
mood_score            float64
emotion                object
recommendation         object
dtype: object

In [13]:
data.nunique()

user_id               89579
age                      63
gender                    3
country                   6
height_cm               591
weight_kg               950
bmi                     241
heart_rate               47
blood_pressure_sys       77
blood_pressure_dia       54
activity_type             6
activity_minutes        113
steps                 13334
calorie_intake         2130
sleep_hours             650
sleep_efficiency        335
sleep_quality            84
water_intake_L          327
hydration_score          74
stress_level              5
mood_score               91
emotion                   4
recommendation           33
dtype: int64